version: '3.9'
services:
  elasticsearch:
    container_name: elastic_search_2
    image: elasticsearch:7.14.2
    ports:
      - "9200:9200"    
      - "9300:9300"    
    networks:
      - dockerinsight 
    volumes:
      - ./es_repo:/usr/share/elasticsearch/es_repo
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      discovery.type: single-node
      path.repo: /usr/share/elasticsearch/es_repo
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  # Remove comments to run CLAVIN experiments
  #clavin:
  #  container_name: clavin_rest_2
  #  image: novetta/clavin-rest
  #  ports:
  #    - "9090:9090"    
  #  networks:
  #    - dockerinsight 
  #  logging:
  #    driver: "json-file"
  #    options:
  #      max-size: "10m"
  #      max-file: "3"
networks:
    dockerinsight:
